### ISSUE TITLE
What files do I need to include cmakepp without downloading it?

### ISSUE THREAD

**Issue by sztomi** [toeb/cmakepp#124]
One example shows how to download cmakepp when it is not available, directly from cmake. While that is very neat, I'm concerned about relying on github (and a working internet connection) for a build. Is there a release I can just drop in the project directory?

**Comment by Manu343726** [comment]
You can always clone the repo pointing at an specific stable commit, then symlink to it in your project. But I'm with you, having a release tag with a tarball would be great. I don't know if @toeb considers cmakepp stable enough to tag a release.

**Comment by toeb** [comment]
Hi,

sure you can download a release from the release section on the github page.  I have already created a couple.  There are compressed files containing the cmake source and a "compiled" version of cmakepp which just puts all functions into a single cmake file of about 1MB size which works standalone.


See https://github.com/toeb/cmakepp/releases 


You can generate this single file yourself by cloning the repository cd to the cmakepp repository and typing 

```
cmake -P cmakepp.cmake cmakepp_compile /path/to/target/file.cmake
```


This will compile all the functionality of cmakepp into the specified target file

**Comment by sztomi** [comment]
Thanks!
