### ISSUE TITLE
Check that rename to cmakepp will not break anything

### ISSUE THREAD

**Issue by toeb** [toeb/cmakepp#67]

**Comment by Manu343726** [comment]
Hi Tobias. 

I have seen your blog post on reddit, congratulations! This is so great. 

About project renaming, I noticed the biicode block toeb/cmakepp is empty :( Completely empty.
Also last week we featured biicode badges, you can get them in the settings page of the block. Here's an example: [![Build Status](https://webapi.biicode.com/v1/badges/manu343726/manu343726/snail/master)](https://www.biicode.com/manu343726/snail)

**Comment by toeb** [comment]
yeah I'm trying to fix it.  just takes a little time ;)
